name: hot_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - bedtools=2.31.0
  - h5py=3.9.0
  - numpy=1.26.0
  - pandas=2.1.1
  - pybedtools=0.9.1
  - scipy=1.11.3
  - seaborn=0.12.2
  - biopython==1.81
  - ipython==8.16.0
  - networkx==3.2.1
  - scikit-learn==1.3.2
  - upsetplot
  - snakemake